<!-- TrustBox widget - Micro Star -->
<li class="nav item">
<div class="trustpilot-widget" data-locale="en-GB" data-template-id="5419b732fbfb950b10de65e5" data-businessunit-id="516ff87100006400052683df" data-style-height="24px" data-style-width="100%" data-theme="light">
    <a href="https://uk.trustpilot.com/review/www.banyo.co.uk" target="_blank" rel="noopener">Trustpilot</a>
</div>
<!-- End TrustBox widget -->
</li>